import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";

const cabinetGrotesk = localFont({
  src: [
    {
      path: './fonts/CabinetGrotesk-Regular.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/CabinetGrotesk-Medium.woff',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/CabinetGrotesk-Bold.woff',
      weight: '900',
      style: 'normal',
    },
  ],
});

export const metadata: Metadata = {
  title: "Hr Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cabinetGrotesk.className}  antialiased`}
      >
      <header className="pt-5"><Navbar /></header>
      <main>{children}</main>
      </body>
    </html>
  );
}
